### ISSUE TITLE
Build failure with Go v1.22/v1.23

### ISSUE THREAD

**Issue by katexochen** [zincsearch/zincsearch#975]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**What were you trying to achieve?**

Building the project.

**What action did you take?**

`go build ./cmd/zincsearch`

**What action/response/output did you expect?**

Successful build.

**What actually happened?**

```
go build ./cmd/zincsearch/
# github.com/pyroscope-io/godeltaprof/internal/pprof
/home/katexochen/go/pkg/mod/github.com/pyroscope-io/godeltaprof@v0.1.2/internal/pprof/delta_mutex.go:25:20: undefined: runtime_cyclesPerSecond
/home/katexochen/go/pkg/mod/github.com/pyroscope-io/godeltaprof@v0.1.2/internal/pprof/proto.go:400:8: undefined: runtime_expandFinalInlineFrame
```

**How to reproduce the issue?**

Build with Go version newer than v1.21 (which is EOL), e.g.,

```
❯ go version
go version go1.22.5 linux/amd64
```

**What version of ZincSearch are you using?**

Tried both latest release (0.4.10) and main branch (a8a490a)

**Anything else that you can tell that will help us diagnose and resolve the issue efficiently?**

/

**Any attachments/screenshots?**

/

**Which service(s) is this relate to?**

/
